-- Tabla Scan
-- CREATE TABLE scan (
--     id SERIAL PRIMARY KEY,
--     nombre VARCHAR,
--     portada TEXT,
--     perfil TEXT,
--     descripcion VARCHAR,
--     redsocial VARCHAR,
--     creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );
-- -- Tabla Puntaje
-- CREATE TABLE puntaje (
--     id SERIAL PRIMARY KEY,
--     usuario_id INT REFERENCES usuario(id),
--     libro_id INT REFERENCES libro(id),
--     calificacion FLOAT,
--     fecha_calificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );
-- -- Tabla Publicador
-- CREATE TABLE publicador (
--     id SERIAL PRIMARY KEY,
--     scan_id INT REFERENCES scan(id),
--     autor_id INT REFERENCES usuario(id),
--     libro_id INT REFERENCES capitulos(id)
-- );
-- -- Tabla Miembros
-- CREATE TABLE miembros (
--     id SERIAL PRIMARY KEY,
--     fk_scan INT REFERENCES scan(id),
--     fk_usuario INT REFERENCES usuario(id)
-- );
-- -- Tabla marcapaginas
-- CREATE TABLE marcapaginas (
--     id SERIAL PRIMARY KEY,
--     fk_usuario INT REFERENCES usuario(id),
--     posicion FLOAT,
--     nota TEXT,
--     etiqueta VARCHAR(50),
--     creado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     actualizado TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     fk_capitulo INT REFERENCES capitulos(id)
-- );

-- migrations/
-- ├── 2026-06-04-xxxxxx_usuario
-- │   ├── usuario
-- │   ├── imagen_perfil
-- │   ├── auth_tokens
-- │   └── token_recuperacion
-- │
-- ├── 2026-06-05-xxxxxx_libro
-- │   ├── novela
-- │   └── imagen_novela
-- │
-- ├── 2026-06-05-xxxxxx_capitulo
-- │   └── capitulo
-- │
-- ├── 2026-06-05-xxxxxx_genero
-- │   ├── genero
-- │   └── novela_genero
-- │
-- ├── 2026-06-05-xxxxxx_biblioteca_usuario
-- │   ├── biblioteca_usuario
-- │   └── progreso_lectura
-- │
-- └── 2026-06-05-xxxxxx_comentario
--     └── comentario